'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million
, find the sum of the even-valued terms.
'''


def main():
    fib = [1,2]
    i = 0
    num = 4000000 
    sum = 0
    while( i < num):
       i = fib[len(fib) - 1] + fib[len(fib) - 2]
       fib.append(i)
    for item in fib:
        if (item % 2 == 0):
            sum += item
    print ("Sum of all even fibonacci numbers less than 4 million is {:d}".format(sum))

if __name__ == '__main__':
    main()
